name: hemend_sentry_log_recorder
description: An extension for Hemend Logger. implements Sentry Log Recorder
version: 0.1.0+4
repository: https://github.com/FMotalleb/hemend_sentry_log_recorder

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ">=0.3.0 <2.0.0"
  test: ^1.19.2
  very_good_analysis: ^5.0.0

dependencies:
  hemend_async_log_recorder: ">=0.0.0 <1.0.0"
  hemend_logger: ">=0.0.0 <1.0.0"
  sentry: ">=7.0.0 <9.0.0"
